<?xml version="1.0"?>
<robot name="car" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Physical Constant Macros -->
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- Dimension Macros -->
    <xacro:property name="carLength" value="2" />
    <xacro:property name="carWidth" value="1.5" />
    <xacro:property name="carHeight" value="0.2" />
    <xacro:property name="wheelRadius" value="0.27" />
    <xacro:property name="wheelWidth" value="0.05" />
    
    <!-- Physical Material Macros -->
    <material name="Red">
    	<color rgba="1.0 0 0 1.0"/>
    </material>
    <material name="Green">
    	<color rgba="0 1.0 0 1.0"/>
    </material>
    <material name="Blue">
    	<color rgba="0 0 1.0 0.5"/>
    </material>
    <material name="Black">
    	<color rgba="0 0 0 1.0"/>
    </material>
    <material name="Aqua">
    	<color rgba="0 255 255 1.0"/>
    </material>


    <!-- Main body -->
    <link name="base_link">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
          <geometry>
             <mesh filename="package://car/meshes/hybrid_body.obj" scale="0.01 0.01 0.01"/>
          </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
        </collision>
    </link>
    
    <!-- Front link of Ackermann -->
    <!-- Joins to the Car body -->
    <joint name="front_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="front_link"/>
    	<origin xyz="${carLength*0.7} 0 0.25" rpy="0 0 0"/>
    </joint>
    <link name="front_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth*1.2} ${carHeight*0.05}" />
            </geometry>
            <material name="Aqua"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth*1.2} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Green</material>
    </gazebo>
    
    <!-- a link aligned with the steer direction -->
    <joint name="steer_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="steer_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </joint>
    <link name="steer_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.2 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0.2 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="steer_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0.0 ${carWidth*0.5} 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_bar_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0.0 ${carWidth*-0.5} 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_right_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_bar_link">
        <material>Gazebo/Green</material>
    </gazebo>

	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_left_bar_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
            <geometry>
		     <mesh filename="package://car/meshes/wheel.obj" scale="0.01 0.01 0.01"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>

	<!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_right_bar_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 -0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
	    <geometry>
		     <mesh filename="package://car/meshes/wheel.obj" scale="0.01 0.01 0.01"/>
	    </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_wheel_link">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

	<!-- the Ackerman bar -->
    <joint name="ackermann_joint" type="revolute" >
        <limit lower="-0.5" upper="0.5" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="steer_link" />
        <child link="ackermann_bar_link" />
        <origin xyz="-0.4 0 0" rpy="0 0 0" />
    </joint>
    <link name="ackermann_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Green</material>
    </gazebo>
    <gazebo reference="ackermann_bar_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    
	<!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="-1.4 ${carWidth*0.5} 0.25" rpy="0 0 0" />
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
            <geometry>
		     <mesh filename="package://car/meshes/wheel.obj" scale="0.01 0.01 0.01"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    
	<!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="-1.4 ${carWidth*-0.5} 0.25" rpy="0 0 0" />
    </joint>
    <link name="back_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
            <geometry>
		     <mesh filename="package://car/meshes/wheel.obj" scale="0.01 0.01 0.01"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    
        <joint name="laser_base_mount_joint" type="fixed">
            <origin xyz="0 0 ${carHeight}" rpy="0 0 0" /> 
            <parent link="base_link"/>
            <child link="laser_base_link"/>
        </joint>
        
        <link name="laser_base_link" type="fixed">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 ${carHeight}"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0.025"/>
                <geometry>
                    <box size="0.05 0.05 0.05"/>
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0.025"/>
                <geometry>
                    <box size="0.05 0.05 0.05"/>
                </geometry>
            </collision>
        </link>
        
        <joint name="base_scan_joint" type="fixed" >
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <parent link="laser_base_link" />
            <child link="base_scan_link"/>
        </joint>
        
        <link name="base_scan_link" type="laser">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0.014"/>
                <geometry>
                    <cylinder radius="0.0229" length="0.028"/>
                </geometry>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0.014"/>
                <geometry>
                    <cylinder radius="0.0229" length="0.028"/>
                </geometry>
            </collision>
        </link>

	  <!-- Camera -->
	  <joint name="camera_joint" type="fixed">
	    <axis xyz="0 0 0" />
	    <origin xyz="1.1 0 ${carHeight*0.8}" rpy="0 0 0"/>
	    <parent link="base_link"/>
	    <child link="camera_link"/>
	  </joint>

	  <link name="camera_link">
	    <collision>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="0.05 0.05 0.05"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="0.05 0.05 0.05"/>
	      </geometry>
	      <material name="red"/>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
	    </inertial>
	  </link>

	  <!-- GPS -->
	  <joint name="gps_joint" type="fixed">
	    <axis xyz="0 0 0" />
	    <origin xyz="0 0 ${carHeight*0.65}" rpy="0 0 0"/>
	    <parent link="base_link"/>
	    <child link="gps_link"/>
	  </joint>

	  <link name="gps_link">
	    <collision>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="0.05 0.05 0.05"/>
	      </geometry>
	    </collision>

	    <visual>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
		<box size="0.05 0.05 0.05"/>
	      </geometry>
	      <material name="green"/>
	    </visual>

	    <inertial>
	      <mass value="1e-5" />
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
	    </inertial>
	  </link>
        
        <gazebo reference="laser_base_link">
            <material>Gazebo/Black</material>
        </gazebo>
	
        <gazebo reference="base_scan_link">
            <material>Gazebo/Black</material>
        </gazebo>

	<!-- GPS. It's a model type, so it needs to attach to a link, not a joint. See bodyName for where this gets attached -->
	<gazebo>
		<plugin name="gps_plugin" filename="libhector_gazebo_ros_gps.so">
			<alwaysOn>1</alwaysOn>
			<updateRate>10.0</updateRate>
			<bodyName>gps_link</bodyName>
			<topicName>gps/fix</topicName>
			<velocityTopicName>gps/fix/velocity</velocityTopicName>
			<drift>5.0 5.0 5.0</drift>
			<gaussianNoise>0.1 0.1 0.1</gaussianNoise>
			<velocityDrift>0 0 0</velocityDrift>
			<velocityGaussianNoise>0.1 0.1 0.1</velocityGaussianNoise>
			<frameId>odom</frameId>
		</plugin>
	</gazebo>


	<gazebo>
		<plugin name="imu_plugin" filename="libhector_gazebo_ros_imu.so">
			<alwaysOn>1</alwaysOn>
			<updateRate>10.0</updateRate>
			<bodyName>base_link</bodyName>
			<topicName>imu/data</topicName>
		</plugin>
	</gazebo>

	  <!-- camera -->
 <gazebo reference="camera_link">
    <sensor type="multicamera" name="stereo_camera">
      <update_rate>30.0</update_rate>
      <camera name="left">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <camera name="right">
        <pose>0 -0.06 0 0 0 0</pose>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>1280</width>
          <height>720</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="stereo_camera_controller" filename="libgazebo_ros_multicamera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>left_camera_optical_frame</frameName>
        <!--<rightFrameName>right_camera_optical_frame</rightFrameName>-->
        <hackBaseline>0.06</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

<!--Must be in same namespace as the spawner in car_control.launch-->
<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/car</robotNamespace>
  </plugin>
</gazebo>

<transmission name="LeftTransmission" type="SimpleTransmission">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="front_left_wheel_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="LeftMotor">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
</transmission>
<transmission name="RightTransmission" type="SimpleTransmission">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="front_right_wheel_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="RightMotor">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
</transmission>
</robot>


